# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('validate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='validate.User')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(max_length=1000)),
                ('rating', models.CharField(max_length=5)),
                ('book_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_book', to='reviews.Book')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_user', to='validate.User')),
            ],
        ),
    ]
