# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20170323_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='book_review',
        ),
        migrations.AddField(
            model_name='review',
            name='book',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reviews.Book'),
            preserve_default=False,
        ),
    ]
