# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseList', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Date_added',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='descripton',
            new_name='description',
        ),
    ]
